version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: acm-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_dev:/data/db

  server:
    container_name: acm-server-dev
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - ./server/.env.development
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    container_name: acm-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file:
      - ./client/.env.development
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo_dev: